### ISSUE TITLE
You require PK 1.10.0, which does not exist. No download for this version is anywhere.

### ISSUE THREAD

**Issue by MagmaSlime123** [StrangeOne101/BendingGUI#13]
![2022-08-28_23 05 09](https://user-images.githubusercontent.com/51277766/187126784-e6876ae9-e3f1-461a-bb30-63921c7a60b4.png)

**Comment by StrangeOne101** [comment]
You are using a release that is for PK 1.10.0, which is available as a test build within the ProjectKorra discord.

For PK 1.9.3, use the history tab on the forums to get the correct version.

![image](https://user-images.githubusercontent.com/2769013/187141488-16d0bc2a-d0bf-416b-b46b-9b7beaf9b7de.png)
