### ISSUE TITLE
Add a README.MD file

### ISSUE THREAD

**Issue by StrangeOne101** [StrangeOne101/BendingGUI#4]
# Overview
A readme file would be appreciated to showcase the basics of this Minecraft/Spigot plugin. It should include graphics of the plugin, a list of features, etc. You can copy a lot of the information from the plugin page at https://projectkorra.com/forum/resources/bendinggui.141/

# Requirements
- Description/features of plugin
- Images showcasing what it looks like in game (using the images from the overview page linked above is fine)
- A rundown of permissions for the plugin
- A rundown on configuring the plugin (the config files, etc)
- The current version of Spigot and ProjectKorra supported by the latest version of the plugin

**Comment by LisaSmith1** [comment]
Was hoping I could work on this?

**Comment by StrangeOne101** [comment]
Sure

**Comment by StrangeOne101** [comment]
Closed, implemented in #9
